### ISSUE TITLE
Construir comparação entre modelos

### ISSUE THREAD

**Issue by arthurTemporim** [SkyNetRecruits/Documentacao#10]
É necessário identificar qual modelo utilizado (knn, decision tree e neural network) é o melhor então a **curva ROC** ou **k.Fold** deve ser implementado em cada notebook para que seja possível relaciondar as soluções.

- [x] KNN
- [ ] Decision Tree
- [x] Neural Network

**Comment by santana-guilherme** [comment]
Apliquei o k-fold no knn
